version: "3"
services:
    web:
        image: "appsvcsample/asp"  
        # the source repo is at https://github.com/yiliaomsft/compose-asp-sql
        ports:
            - "8080:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
